@startuml
skinparam ClassFontStyle bold
skinparam ClassBackgroundColor ffffff
skinparam ClassBorderColor 5a0000
skinparam RoundCorner 0
skinparam ClassBorderThickness 2
hide empty fields
hide empty methods
skinparam Shadowing true
skinparam BackgroundColor transparent
class "AutogramSdkException" {
    +<b>code</b> : AutogramErrorCode
    {static} +fromJSON(data: unknown) : AutogramError
    {static} +is(e: unknown, code: AutogramErrorCode) : e is AutogramError
    +toJSON() : SerializedAutogramError
}
class "AutogramError" {
    +<b>code</b> : AutogramErrorCode
    {static} +fromJSON(data: unknown) : AutogramError
    {static} +is(e: unknown, code: AutogramErrorCode) : e is AutogramError
    +toJSON() : SerializedAutogramError
}
"AutogramError" <|-- "AutogramSdkException"
class "AutogramAppNotInstalledException" {
    +<b>code</b> : AutogramErrorCode
    {static} +fromJSON(data: unknown) : AutogramError
    {static} +is(e: unknown, code: AutogramErrorCode) : e is AutogramError
    +toJSON() : SerializedAutogramError
}
"AutogramSdkException" <|-- "AutogramAppNotInstalledException"
@enduml